apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-ReplicaSet
  namespace: mj-eks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx
    template:
      metadata:
        labels:
          app: my-nginx
      spec:
        containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: mj-eks
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-nginx